In [35]:
import pandas as pd
import requests
import sqlite3

In [36]:
# --EXTRACT DATA--
url = 'https://anime-db.p.rapidapi.com/anime?page=1&size=10&search=Fullmetal&genres=Fantasy%2CDrama&sortBy=ranking&sortOrder=asc'

In [ ]:
header = {
    'X-RapidAPI-Key' : 'rapid_key',
    'X-RapidAPI-Host' : 'anime-db.p.rapidapi.com'
}

In [38]:
response = requests.get(url, headers=header)

In [39]:
data_json  = response.json()

In [40]:
print(data_json)

{'data': [{'_id': '5114', 'id': '5114', '__v': 1, 'title': 'Fullmetal Alchemist: Brotherhood', 'alternativeTitles': ['Hagane no Renkinjutsushi: Fullmetal Alchemist', 'Fullmetal Alchemist (2009)', 'FMA', 'FMAB', '鋼の錬金術師 FULLMETAL ALCHEMIST', 'Fullmetal Alchemist: Brotherhood', 'Fullmetal Alchemist Brotherhood'], 'genres': ['Action', 'Adventure', 'Drama', 'Fantasy'], 'image': 'https://cdn.myanimelist.net/images/anime/1208/94745.jpg', 'thumb': 'https://cdn.myanimelist.net/r/50x70/images/anime/1208/94745.jpg?s=7892d01b6c74f1bf945f7a3ff3bb1f6a', 'link': 'https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood', 'ranking': 3, 'synopsis': 'After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality. Ignoring the alchemical principle banning human transmutation, the boys attempted to bring their recently deceased mother back to life. Instead, they suffered brutal personal loss: Alphonse\'s body disintegrated while Edward lost a leg and then sacrificed an arm to keep Alphonse\'s soul in the physical realm by binding it to a hulking suit of armor.\n\nThe brothers are rescued by their neighbor Pinako Rockbell and her granddaughter Winry. Known as a bio-mechanical engineering prodigy, Winry creates prosthetic limbs for Edward by utilizing "automail," a tough, versatile metal used in robots and combat armor. After years of training, the Elric brothers set off on a quest to restore their bodies by locating the Philosopher\'s Stone—a powerful gem that allows an alchemist to defy the traditional laws of Equivalent Exchange.\n\nAs Edward becomes an infamous alchemist and gains the nickname "Fullmetal," the boys\' journey embroils them in a growing conspiracy that threatens the fate of the world.\n\n[Written by MAL Rewrite]', 'episodes': 64, 'status': 'Finished Airing', 'type': 'TV', 'hasRanking': True, 'hasEpisode': True, 'updatedAt': None, 'workerId': 'qk0af'}, {'_id': '121', 'id': '121', '__v': 1, 'title': 'Fullmetal Alchemist', 'alternativeTitles': ['Hagane no Renkinjutsushi', 'FMA', 'Full Metal Alchemist', '鋼の錬金術師', 'Fullmetal Alchemist'], 'genres': ['Action', 'Adventure', 'Award Winning', 'Drama', 'Fantasy'], 'image': 'https://cdn.myanimelist.net/images/anime/10/75815.jpg', 'thumb': 'https://cdn.myanimelist.net/r/50x70/images/anime/10/75815.jpg?s=095ef966da07a873a75e38378080a466', 'link': 'https://myanimelist.net/anime/121/Fullmetal_Alchemist', 'ranking': 554, 'synopsis': "Edward Elric, a young, brilliant alchemist, has lost much in his twelve-year life: when he and his brother Alphonse try to resurrect their dead mother through the forbidden act of human transmutation, Edward loses his brother as well as two of his limbs. With his supreme alchemy skills, Edward binds Alphonse's soul to a large suit of armor.\n\nA year later, Edward, now promoted to the fullmetal alchemist of the state, embarks on a journey with his younger brother to obtain the Philosopher's Stone. The fabled mythical object is rumored to be capable of amplifying an alchemist's abilities by leaps and bounds, thus allowing them to override the fundamental law of alchemy: to gain something, an alchemist must sacrifice something of equal value. Edward hopes to draw into the military's resources to find the fabled stone and restore his and Alphonse's bodies to normal. However, the Elric brothers soon discover that there is more to the legendary stone than meets the eye, as they are led to the epicenter of a far darker battle than they could have ever imagined.\n\n[Written by MAL Rewrite]", 'episodes': 51, 'status': 'Finished Airing', 'type': 'TV', 'hasRanking': True, 'hasEpisode': True, 'updatedAt': None, 'workerId': 'qk0af'}, {'_id': '6421', 'id': '6421', '__v': 1, 'title': 'Fullmetal Alchemist: Brotherhood Specials', 'alternativeTitles': ['Moumoku no Renkinjutsushi', 'The Blind Alchemist', 'Shinpuru na Hitobito', 'Simple People', 'The Tale of Teacher', 'Tales of the Master', "Yet Another Man's Battlefield", 'FMA', '鋼の錬金術師', 'Fullmetal Alchemist: Brotherhood OVA Collection', 'Fullmetal Alchemist: Brootherhood OVA Collection', 'Fullmetal Alchemist: Brotherhood OAV Collection'], 'genres': ['Action', 'Adventure', 'Drama', 'Fantasy'], 'image': 'https://cdn.myanimelist.net/images/anime/1493/91571.jpg', 'thumb': 'https://cdn.myanimelist.net/r/50x70/images/anime/1493/91571.jpg?s=f2446fd02aa660c9db22746d3f5f2cf3', 'link': 'https://myanimelist.net/anime/6421/Fullmetal_Alchemist__Brotherhood_Specials', 'ranking': 739, 'synopsis': "1. Moumoku no Renkinjutsushi (The Blind Alchemist)\n2. Simple na Hitobito (Simple People)\n3. Sensei Monogatari (The Tale of Teacher)\n4. Sore mo mata Kare no Senjou (Yet Another Man's Battlefield)", 'episodes': 4, 'status': 'Finished Airing', 'type': 'Special', 'hasRanking': True, 'hasEpisode': True, 'updatedAt': None, 'workerId': 'qk0af'}, {'_id': '430', 'id': '430', '__v': None, 'title': 'Fullmetal Alchemist: The Conqueror of Shamballa', 'alternativeTitles': ['Gekijyouban Hagane no Renkinjutsushi - Shanbara wo Yuku Mono', 'Fullmetal Alchemist the Movie: Conqueror of Shamballa', 'FMA Movie', '劇場版 鋼の錬金術師 シャンバラを征く者', 'Fullmetal Alchemist: The Movie - Conqueror of Shamballa', 'Fullmetal Alchemist: Der Eroberer von Shamballa', 'Fullmetal Alchemist: El Conquistador de Shamballa', 'Fullmetal Alchemist: Conqueror of shamballa'], 'genres': ['Action', 'Adventure', 'Award Winning', 'Drama', 'Fantasy'], 'image': 'https://cdn.myanimelist.net/images/anime/1707/94039.jpg', 'thumb': 'https://cdn.myanimelist.net/r/50x70/images/anime/1707/94039.jpg?s=a4e0a259b6d9cee5d327d704e8e5ea37', 'link': 'https://myanimelist.net/anime/430/Fullmetal_Alchemist__The_Conqueror_of_Shamballa', 'ranking': 2147, 'synopsis': "In desperation, Edward Elric sacrificed his body and soul to rescue his brother Alphonse, and is now displaced in the heart of Munich, Germany. He struggles to adapt to a world completely foreign to him in the wake of the economic crisis that followed the end of World War I. Isolated and unable to return home with his alchemy skills, Edward continues to research other methods of escaping the prison alongside colleagues who bear striking resemblances to many of the people he left behind. As dissent brews among the German citizenry, its neighbors also feel the unrest of the humiliated nation.\n\nMeanwhile, Alphonse continues to investigate Edward's disappearance, delving into the science of alchemy in the hopes of finally reuniting with his older brother. \n\n[Written by MAL Rewrite]", 'episodes': 1, 'status': 'Finished Airing', 'type': 'Movie', 'hasRanking': True, 'hasEpisode': True, 'updatedAt': None, 'workerId': 'qk0af'}, {'_id': '7902', 'id': '7902', '__v': 1, 'title': 'Fullmetal Alchemist: Brotherhood - 4-koma Gekijou', 'alternativeTitles': ['Hagane no Renkinjutsushi: Hagaren 4-koma Gekijou', 'Hiromu Arakawa 4-koma Theater', 'FMA: 4-koma Theater', '荒川弘 描き下ろし4コマ劇場', 'Fullmetal Alchemist: Brotherhood 4-koma Theater'], 'genres': ['Comedy', 'Fantasy'], 'image': 'https://cdn.myanimelist.net/images/anime/3/76154.jpg', 'thumb': 'https://cdn.myanimelist.net/r/50x70/images/anime/3/76154.jpg?s=3be1c23dd376fff1112caffecb5067a2', 'link': 'https://myanimelist.net/anime/7902/Fullmetal_Alchemist__Brotherhood_-_4-koma_Gekijou', 'ranking': 2402, 'synopsis': 'Short specials from the DVDs/BDs.', 'episodes': 16, 'status': 'Finished Airing', 'type': 'Special', 'hasRanking': True, 'hasEpisode': True, 'updatedAt': None, 'workerId': 'qk0af'}, {'_id': '908', 'id': '908', '__v': 1, 'title': 'Fullmetal Alchemist: Premium Collection', 'alternativeTitles': ['State Alchemists vs Seven Homunculi', 'Enkai-hen', 'Chibi Party', 'Kodomo-hen', 'Kids', 'FMA', '鋼の錬金術師 PREMIUM COLLECTION', 'Fullmetal Alchemist: Premium OVA Collection'], 'genres': ['Comedy', 'Fantasy'], 'image': 'https://cdn.myanimelist.net/images/anime/10/18689.jpg', 'thumb': 'https://cdn.myanimelist.net/r/50x70/images/anime/10/18689.jpg?s=1f8c88088c285bda1be8e8d0d903b10c', 'link': 'https://myanimelist.net/anime/908/Fullmetal_Alchemist__Premium_Collection', 'ranking': 3138, 'synopsis': '1. State Alchemists vs Seven Homunculi\nA 10 minute film featuring: Ed, Al, Mustang and many other members of the State doing battle with the deadly Homonculi in an alternate reality Amestris.\n\n2. Chibi Party (Enkai-hen)\nShort 6 minute Skit drawn in Super Deformed style where every character in the series (including bad guys) are celebrating an "After Party" of the Conqueror of Shambala movie.\n\n3. Kids (Kodomo-hen)\nShort 3 minute story which features Edward and his grandkids in present day 2005.\n\n(Source: ANN) ', 'episodes': 3, 'status': 'Finished Airing', 'type': 'OVA', 'hasRanking': True, 'hasEpisode': True, 'updatedAt': None, 'workerId': 'qk0af'}, {'_id': '9135', 'id': '9135', '__v': 1, 'title': 'Fullmetal Alchemist: The Sacred Star of Milos', 'alternativeTitles': ['Fullmetal Alchemist: Milos no Seinaru Hoshi', 'Fullmetal Alchemist Movie 2', 'Hagane no Renkinjutsushi Movie 2', 'FMA Movie 2', '劇場版 鋼の錬金術師 嘆きの丘(ミロス)の聖なる星', 'Fullmetal Alchemist: The Sacred Star of Milos', 'Fullmetal Alchemist: The sacred Star of Milos', 'Fullmetal Alchemist: La Estrella Sagrada de Milos', "Fullmetal Alchemist: L'Étoile Sacrée de Milos"], 'genres': ['Action', 'Adventure', 'Drama', 'Fantasy'], 'image': 'https://cdn.myanimelist.net/images/anime/1217/152912.jpg', 'thumb': 'https://cdn.myanimelist.net/r/50x70/images/anime/1217/152912.jpg?s=b7bf564201fe9b117422c844d7bb45bf', 'link': 'https://myanimelist.net/anime/9135/Fullmetal_Alchemist__The_Sacred_Star_of_Milos', 'ranking': 3299, 'synopsis': "Chasing a runaway alchemist with strange powers, brothers Edward and Alphonse Elric stumble into the squalid valley of the Milos. The Milosians are an oppressed group that seek to reclaim their holy land from Creta: a militaristic country that forcefully annexed their nation. In the eye of the political storm is a girl named Julia Crichton, who emphatically wishes for the Milos to regain their strength and return to being a nation of peace.\n\nBefriending the girl, Edward and Alphonse find themselves in the midst of a rising resistance that involves the use of the very object they have been seeking all along—the Philosopher's Stone. However, their past experiences with the stone cause them reservation, and the brothers are unwilling to help.\n\nBut as they discover the secrets behind Creta's intentions and questionable history, the brothers are drawn into the battle between the rebellious Milos, who desire their liberty, and the Cretan military, who seek absolute power.\n\n[Written by MAL Rewrite]", 'episodes': 1, 'status': 'Finished Airing', 'type': 'Movie', 'hasRanking': True, 'hasEpisode': True, 'updatedAt': None, 'workerId': 'qk0af'}, {'_id': '664', 'id': '664', '__v': 1, 'title': 'Fullmetal Alchemist: Reflections', 'alternativeTitles': ['Hagane no Renkinjutsushi: Tabi no Hajimari', 'FMA: Reflections', '鋼の錬金術師 旅の始まり'], 'genres': ['Adventure', 'Comedy', 'Drama', 'Fantasy'], 'image': 'https://cdn.myanimelist.net/images/anime/2/18690.jpg', 'thumb': 'https://cdn.myanimelist.net/r/50x70/images/anime/2/18690.jpg?s=38dc7aee576c5d2c2367c1200e14d700', 'link': 'https://myanimelist.net/anime/664/Fullmetal_Alchemist__Reflections', 'ranking': 3548, 'synopsis': 'A reflection on what happened during the FMA TV series.', 'episodes': 1, 'status': 'Finished Airing', 'type': 'Special', 'hasRanking': True, 'hasEpisode': True, 'updatedAt': None, 'workerId': 'qk0af'}, {'_id': '10842', 'id': '10842', '__v': 1, 'title': 'Fullmetal Alchemist: The Sacred Star of Milos Specials', 'alternativeTitles': ['Hagane no Renkinjutsushi: Milos no Seinaru Hoshi PV', 'FMA Movie 2 PV', '鋼の錬金術師 嘆きの丘[ミロス]の聖なる星 特別動画', 'Fullmetal Alchemist: The Sacred Star of Milos PV'], 'genres': ['Comedy', 'Fantasy'], 'image': 'https://cdn.myanimelist.net/images/anime/9/29928.jpg', 'thumb': 'https://cdn.myanimelist.net/r/50x70/images/anime/9/29928.jpg?s=e61b7fcae7a0152292f9a6c12f1ef549', 'link': 'https://myanimelist.net/anime/10842/Fullmetal_Alchemist__The_Sacred_Star_of_Milos_Specials', 'ranking': 5962, 'synopsis': 'To mark the July 2 opening of the Fullmetal Alchemist: The Sacred Star of Milos film, the Pia Eiga Seikatsu website posted an exclusive video "interview" with the stars of the film, Edward and Alphonse Elric (as voiced by Romi Park and Rie Kugimiya, respectively). In keeping with the spirit of Hiromu Arakawa\'s original manga and the two television anime, the interviewer has trouble early on in figuring out who the "Fullmetal Alchemist" is. (The interview has cameos by the other stars of the anime.) Also includes 3 "Study" sessions with "Professor" Mustang, teaching Winry and Hawkeye about Creta and Milos.', 'episodes': 4, 'status': 'Finished Airing', 'type': 'ONA', 'hasRanking': True, 'hasEpisode': True, 'updatedAt': None, 'workerId': 'qk0af'}], 'meta': {'page': 1, 'size': 10, 'totalData': 9, 'totalPage': 1}}

In [41]:
# -- CEK STRUKTUR KUNCI API SEBELUM DIUBAH KE TABLE --
print(data_json.keys())

dict_keys(['data', 'meta'])

In [42]:
df = pd.DataFrame(data_json['data'])

In [43]:
df.head()

,_id,id,__v,title,alternativeTitles,genres,image,thumb,link,ranking,synopsis,episodes,status,type,hasRanking,hasEpisode,updatedAt,workerId
0,5114,5114,1.0,Fullmetal Alchemist: Brotherhood,[Hagane no Renkinjutsushi: Fullmetal Alchemist...,"[Action, Adventure, Drama, Fantasy]",https://cdn.myanimelist.net/images/anime/1208/...,https://cdn.myanimelist.net/r/50x70/images/ani...,https://myanimelist.net/anime/5114/Fullmetal_A...,3,After a horrific alchemy experiment goes wrong...,64,Finished Airing,TV,True,True,None,qk0af
1,121,121,1.0,Fullmetal Alchemist,"[Hagane no Renkinjutsushi, FMA, Full Metal Alc...","[Action, Adventure, Award Winning, Drama, Fant...",https://cdn.myanimelist.net/images/anime/10/75...,https://cdn.myanimelist.net/r/50x70/images/ani...,https://myanimelist.net/anime/121/Fullmetal_Al...,554,"Edward Elric, a young, brilliant alchemist, ha...",51,Finished Airing,TV,True,True,None,qk0af
2,6421,6421,1.0,Fullmetal Alchemist: Brotherhood Specials,"[Moumoku no Renkinjutsushi, The Blind Alchemis...","[Action, Adventure, Drama, Fantasy]",https://cdn.myanimelist.net/images/anime/1493/...,https://cdn.myanimelist.net/r/50x70/images/ani...,https://myanimelist.net/anime/6421/Fullmetal_A...,739,1. Moumoku no Renkinjutsushi (The Blind Alchem...,4,Finished Airing,Special,True,True,None,qk0af
3,430,430,NaN,Fullmetal Alchemist: The Conqueror of Shamballa,[Gekijyouban Hagane no Renkinjutsushi - Shanba...,"[Action, Adventure, Award Winning, Drama, Fant...",https://cdn.myanimelist.net/images/anime/1707/...,https://cdn.myanimelist.net/r/50x70/images/ani...,https://myanimelist.net/anime/430/Fullmetal_Al...,2147,"In desperation, Edward Elric sacrificed his bo...",1,Finished Airing,Movie,True,True,None,qk0af
4,7902,7902,1.0,Fullmetal Alchemist: Brotherhood - 4-koma Gekijou,[Hagane no Renkinjutsushi: Hagaren 4-koma Geki...,"[Comedy, Fantasy]",https://cdn.myanimelist.net/images/anime/3/761...,https://cdn.myanimelist.net/r/50x70/images/ani...,https://myanimelist.net/anime/7902/Fullmetal_A...,2402,Short specials from the DVDs/BDs.,16,Finished Airing,Special,True,True,None,qk0af

In [44]:
# --TRANSFORM--
df['genres'] = df['genres'].apply(lambda x: ','. join(x) if isinstance(x, list) else x)
df['alternativeTitles'] = df['alternativeTitles'].apply(lambda x: ','. join(x) if isinstance(x, list) else x)

In [45]:
#-- LOAD (masukin ke sql) --
conn = sqlite3.connect('anime_database.db')

In [46]:
df.to_sql('table_anime', conn, if_exists='replace', index=False)

9

In [47]:
conn.close()

In [48]:
print('ETL SUCCESS')

ETL SUCCESS

In [49]:
df.head()

,_id,id,__v,title,alternativeTitles,genres,image,thumb,link,ranking,synopsis,episodes,status,type,hasRanking,hasEpisode,updatedAt,workerId
0,5114,5114,1.0,Fullmetal Alchemist: Brotherhood,"Hagane no Renkinjutsushi: Fullmetal Alchemist,...","Action,Adventure,Drama,Fantasy",https://cdn.myanimelist.net/images/anime/1208/...,https://cdn.myanimelist.net/r/50x70/images/ani...,https://myanimelist.net/anime/5114/Fullmetal_A...,3,After a horrific alchemy experiment goes wrong...,64,Finished Airing,TV,True,True,None,qk0af
1,121,121,1.0,Fullmetal Alchemist,"Hagane no Renkinjutsushi,FMA,Full Metal Alchem...","Action,Adventure,Award Winning,Drama,Fantasy",https://cdn.myanimelist.net/images/anime/10/75...,https://cdn.myanimelist.net/r/50x70/images/ani...,https://myanimelist.net/anime/121/Fullmetal_Al...,554,"Edward Elric, a young, brilliant alchemist, ha...",51,Finished Airing,TV,True,True,None,qk0af
2,6421,6421,1.0,Fullmetal Alchemist: Brotherhood Specials,"Moumoku no Renkinjutsushi,The Blind Alchemist,...","Action,Adventure,Drama,Fantasy",https://cdn.myanimelist.net/images/anime/1493/...,https://cdn.myanimelist.net/r/50x70/images/ani...,https://myanimelist.net/anime/6421/Fullmetal_A...,739,1. Moumoku no Renkinjutsushi (The Blind Alchem...,4,Finished Airing,Special,True,True,None,qk0af
3,430,430,NaN,Fullmetal Alchemist: The Conqueror of Shamballa,Gekijyouban Hagane no Renkinjutsushi - Shanbar...,"Action,Adventure,Award Winning,Drama,Fantasy",https://cdn.myanimelist.net/images/anime/1707/...,https://cdn.myanimelist.net/r/50x70/images/ani...,https://myanimelist.net/anime/430/Fullmetal_Al...,2147,"In desperation, Edward Elric sacrificed his bo...",1,Finished Airing,Movie,True,True,None,qk0af
4,7902,7902,1.0,Fullmetal Alchemist: Brotherhood - 4-koma Gekijou,Hagane no Renkinjutsushi: Hagaren 4-koma Gekij...,"Comedy,Fantasy",https://cdn.myanimelist.net/images/anime/3/761...,https://cdn.myanimelist.net/r/50x70/images/ani...,https://myanimelist.net/anime/7902/Fullmetal_A...,2402,Short specials from the DVDs/BDs.,16,Finished Airing,Special,True,True,None,qk0af